Move e2e tests

diff --git a/.github/workflows/end2end_test.yml b/.github/workflows/end2end_test.yml
--- a/.github/workflows/end2end_test.yml
+++ b/.github/workflows/end2end_test.yml
@@ -79,7 +79,7 @@ jobs:
           # No need to download a cached version in cache preparation step
           lookup-only: true
           path: &cache-example-dataset-path lightly_studio/datasets
-          key: &cache-example-dataset-key coco-example-dataset
+          key: &cache-example-dataset-key example-dataset
 
 
       ### Setup steps for the workflow ###
@@ -285,6 +285,147 @@ jobs:
         if: always()
         run: |
           kill ${{ env.SERVER_PID }} || true
+
+  # end-to-end-test-captions:
+  #   name: End2End Test with Captions
+  #   runs-on: ubuntu-latest
+  #   needs: prepare-caches
+  #   # Skip the job if there's no change that affects end-to-end tests.
+  #   if: needs.prepare-caches.outputs.cache-hit != 'true'
+  #   steps:
+  #     - name: Checkout Code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         submodules: recursive
+
+  #     # Authenticate to download lightly-edge-sdk.
+  #     - name: Authenticate with GCP
+  #       uses: 'google-github-actions/auth@v2'
+  #       with:
+  #         project_id: boris-250909
+  #         credentials_json: ${{ secrets.GCP_LIGHTLY_STUDIO_CI_READONLY }}
+
+  #     ### Restore caches ###
+      
+  #     - name: Cache build
+  #       id: cache-build
+  #       uses: actions/cache@v4
+  #       with:
+  #         fail-on-cache-miss: true
+  #         path: *cache-build-path
+  #         key: *cache-build-key
+
+  #     - name: Cache Playwright browsers
+  #       id: cache-playwright-browsers
+  #       uses: actions/cache@v4
+  #       with:
+  #         fail-on-cache-miss: true
+  #         path: *cache-playwright-browsers-path
+  #         key: *cache-playwright-browsers-key
+
+  #     - name: Cache example dataset
+  #       id: cache-example-dataset
+  #       uses: actions/cache@v4
+  #       with:
+  #         fail-on-cache-miss: true
+  #         path: *cache-example-dataset-path
+  #         key: *cache-example-dataset-key
+
+  #     ### Setup ###
+
+  #     - name: Set Up Python
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: "3.8"
+
+  #     - name: Set Up Uv
+  #       uses: astral-sh/setup-uv@v6
+  #       with:
+  #         version: "0.8.17"
+  #         enable-cache: true
+
+  #     - name: Set Up Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: '22.11.0'
+  #         cache: 'npm'
+  #         cache-dependency-path: lightly_studio_view/package-lock.json
+
+  #     - name: Install lightly_studio_view dependencies
+  #       working-directory: lightly_studio_view
+  #       run: npm ci
+
+  #     - name: Install lightly_studio python dependencies
+  #       working-directory: lightly_studio
+  #       run: make install-optional-deps
+
+  #     ### Run e2e tests ###
+      
+  #     - name: Index dataset with using lightly_studio pypi package
+  #       working-directory: lightly_studio
+  #       # TODO(Michal, 10/2025): Starting up the server redownloads the embedding model. Consider caching it.
+  #       run: |
+  #         uv run e2e-tests/index_dataset_for_end2end_ui_tests.py > server.log 2>&1 &
+  #         echo "SERVER_PID=$!" >> $GITHUB_ENV
+  #       id: server
+
+  #     - name: Wait for the server to start
+  #       timeout-minutes: 5
+  #       working-directory: lightly_studio
+  #       run: |
+  #         echo "Waiting for the server to become available..."
+  #         timeout=360
+  #         elapsed=0
+  #         interval=5
+          
+  #         while [ $elapsed -lt $timeout ]; do
+  #           if curl -s -f ${E2E_BASE_URL}/healthz > /dev/null 2>&1; then
+  #             echo "✅ Server is up and running after ${elapsed} seconds!"
+  #             break
+  #           fi
+  #           if ! ps -p ${{ env.SERVER_PID }} > /dev/null; then
+  #             echo "❌ Server process has exited unexpectedly."
+  #             exit 1
+  #           fi
+
+  #           echo "⏳ Server not ready yet, waiting... (${elapsed}/${timeout} seconds)"
+  #           tail -n 1 server.log
+  #           echo
+  #           sleep $interval
+  #           elapsed=$((elapsed + interval))
+  #         done
+          
+  #         if [ $elapsed -ge $timeout ]; then
+  #           echo "❌ Timed out waiting for server to become available"
+  #           exit 1
+  #         fi
+
+  #     ### Running end-to-end tests ###
+  #     - name: Run end-to-end tests for indexed dataset
+  #       working-directory: lightly_studio_view
+  #       run: npx playwright test --reporter=html --trace=on
+  #       timeout-minutes: 10
+      
+  #     ### Cleanup steps for the workflow ###
+  #     - name: Show server logs after failure
+  #       if: failure()
+  #       working-directory: lightly_studio
+  #       run: |
+  #         echo "Server logs:"
+  #         cat server.log
+
+  #     - name: Upload Playwright report after failure
+  #       uses: actions/upload-artifact@v4
+  #       if: failure()
+  #       with:
+  #         name: Upload Playwright Report
+  #         path: lightly_studio_view/playwright-report
+  #         retention-days: 5
+
+  #     - name: Stop lightly_studio application running in background
+  #       if: always()
+  #       run: |
+  #         kill ${{ env.SERVER_PID }} || true
 
   success-check:
     name: Success Check
